name: 'Docker Build Branch'
on:
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: 'Branch Publish'
    if: contains(github.event.pull_request.labels.*.name, 'smoketest') == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Calculate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 'quay.io/ukhomeofficedigital/hocs-helm-kubectl'
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
